name: Spacecraft CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    name: Audit Dependencies
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.0.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run audit-dependencies

  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.0.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build

  lint:
    name: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.0.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint

  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.0.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
